# Generated by Django 4.2.15 on 2025-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCatUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, help_text="UID Firebase de l'utilisateur", max_length=255)),
                ('phone', models.CharField(db_index=True, help_text='Numéro de téléphone (hashé pour RevenueCat)', max_length=50)),
                ('app_user_id', models.CharField(db_index=True, help_text='App User ID RevenueCat (hash du téléphone)', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Premium actif'), ('trial', 'Essai en cours'), ('grace', 'Grace period'), ('expired', 'Abonnement expiré'), ('none', 'Gratuit')], default='none', max_length=20)),
                ('status_label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('is_sandbox_entitlement', models.BooleanField(default=False)),
                ('is_sandbox_subscription', models.BooleanField(blank=True, null=True)),
                ('product_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('period_type', models.CharField(blank=True, max_length=50, null=True)),
                ('will_renew', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('grace_period_expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text="Données brutes complètes de l'API RevenueCat")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'revenuecat_user_status',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uid', '-created_at'], name='revenuecat__uid_ac258a_idx'), models.Index(fields=['phone', '-created_at'], name='revenuecat__phone_2f8584_idx'), models.Index(fields=['status', '-created_at'], name='revenuecat__status_5fa7d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueCatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('app_user_id', models.CharField(db_index=True, max_length=255)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Premium actif'), ('trial', 'Essai en cours'), ('grace', 'Grace period'), ('expired', 'Abonnement expiré'), ('none', 'Gratuit')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('product_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'revenuecat_history',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['uid', '-snapshot_date'], name='revenuecat__uid_47770d_idx'), models.Index(fields=['snapshot_date'], name='revenuecat__snapsho_7165dd_idx')],
                'unique_together': {('uid', 'snapshot_date')},
            },
        ),
    ]
